### ISSUE TITLE
Get check urls in promise

### ISSUE THREAD

**Issue by lukasoppermann** [actuallymentor/check-broken-links#1]
Hey,

it would be helpful to get all links in the response promise, not just the broken ones. I am using this for testing and would like to show the valid links as well.

**Comment by actuallymentor** [comment]
Hey!

I added that option in version 2.0.1. The output object now looks like:

```js
{ top: [], crawled: [], allchecked: [[ }
```

Where allchecked is all crawled links and where they came from.

Note that the object structure changed a bit going from version 1.x to 2.x so check back with the readme.
